steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.frontend
      - -t
      - southamerica-east1-docker.pkg.dev/data-analysis-questions/cloud-run-source-deploy/ga4-chat-frontend:latest
      - .
images:
  - southamerica-east1-docker.pkg.dev/data-analysis-questions/cloud-run-source-deploy/ga4-chat-frontend:latest
